config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts

  get 'categories/new' => 'categories#new', as: :new_category
  get 'categories/:id' => 'categories#show', as: :category
  post 'categories' => 'categories#create'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true

  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
  validates :category_id, presence: true

  belongs_to :category

  def post_date
    self.created_at.strftime("%B %d, %Y")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  respond_to :html, :json

  def new
    @category = Category.new
  end

  def show
   @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category successfully created!"
    else
      flash[:notice] = "Error: category not created"
    end
    respond_with(@category, location: new_post_url)
  end

  private

  def category_params
    params.require(:category).permit!
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  respond_to :html, :json

  def index
    @posts = Post.all.reverse
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post successfully created!"
    else
      flash[:notice] = "Error: Post not created"
    end
    respond_with(@post)
  end

  def show
    @post = Post.find(params[:id])
    @post_date = @post.post_date
  end

  private

  def post_params
    params.require(:post).permit!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_categories
    Category.all
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def display_sidebar?
    true
  end
end

app/views/categories/_names.html.erb
  <% display_categories.each do |category| %>
    <li><%= link_to "#{category.name}", category_path("#{category.id}") %></li>
  <% end %>

app/views/categories/new.html.erb
<%= form_for(@category) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<% @category.posts.reverse.each do |post| %>
  <%= render 'posts/preview', :post => post %>
<% end %>

app/views/layouts/_top_nav_bar.html.erb
<div class="contain-to-grid">
   <nav class="top-bar" data-topbar role="navigation" data-options="is_hover: false" >
    <ul class="title-area">
      <li class="name">
        <h1 id="logo">Frank DelPidio</h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="/"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li><a href="#">Portfolio</a></li>
        <li><%= link_to "Blog", posts_url %></li>
        <li><a href="#">About Me</a></li>
        <li><a href="#">Contact</a></li>

      </ul>

      <ul class="left">
        <li id="developer">Web Developer</li>
      </ul>
      </section>
    </nav>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
        <%= render "layouts/top_nav_bar" %>
      </div>
    </div>
    <div class="row">
      <div class="small-8 column">
        <%= yield %>
      </div>
      <div class="small-3 column">
        <% if display_sidebar? %>
          <ul class="side-nav">
            <li><%= link_to "All Posts", root_url %></li>
            <%= render "categories/names" %>
          </ul>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">
  <%= form_for(@post) do |f| %>
    <div class="row">
      <div class="small-12 columns">
         <%= f.text_field :title, placeholder: "Title" %>
      </div>
    </div>
  <div class="row">
    <div class="small-9 columns">
      <%= f.select(:category_id) do %>
        <% display_categories.each do |category| %>
          <%= content_tag(:option, category.name, value: category.id) %>
        <% end %>
      <% end %>
    </div>
    <div class="small-3 columns">
      <%= link_to 'New Category', new_category_url %>
    </div>
  </div>

      <%= f.text_area :body, rows: 15 %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/_preview.html.erb
<ul class="post-preview">
  <li class="post-title"><%= link_to "#{post.title}", post_path("#{post.id}") %><br>
  <span class="post-preview-date"><%= post.post_date %></span></li>
  <li class="post-category">#<%= post.category.name %></li>
  <li class= "post-preview-body"><%= simple_format post.body.first(500) %><%= link_to "Read More", post_path("#{post.id}") %></li>
</ul>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<% @posts.each do |post| %>
  <%= render 'preview', :post => post %>
<% end %>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="post-title"><%= @post.title %></div>
<div class="post-date"><%= @post_date %></div>
<div class="post-body"><%= simple_format @post.body %></div>